.TH "Arc" 3 "Sun Oct 30 2022" "LabBook1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArc\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBArc\fP (sf::Vector2f p1, float p2, float p3, float radianValue, sf::Color c1)"
.br
.RI "Overloaded constructor\&. "
.ti -1c
.RI "void \fBdraw\fP (sf::RenderTarget &target, sf::RenderStates states) const override"
.br
.RI "Instantiated draw function\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is the \fBArc\fP class\&. This includes the basic constructor, overloaded constructor to take the position of the \fBArc\fP when drawn to the screen and the overridden draw function, which is used to draw the shape itself to the screen, once an object has been created in the main function to do so\&. This class also includes access to the public functions (or protected) from the \fBCircularData\fP class, which includes the value for pi, theta and radian value\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Arc::Arc ()"

.PP
Constructor\&. Default constructor\&. 
.SS "Arc::Arc (sf::Vector2f p1, float p2, float p3, float radianValue, sf::Color c1)"

.PP
Overloaded constructor\&. Overloaded constructor to take the central point of the arc, the size of the arc, color, the size of the vertex array and the radian value to be passed back to the \fBCircularData\fP class\&. In this instance, the radian value is customisable in the main so that the arc's angle can be manipulated, producing a larger or smaller arc\&. The For loop will increment by 1 each time a line has been drawn and draw the next line until the conditions have been met, ie, the For loop has gotten to 60\&. It will also apply the selected colour to each line\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Arc::draw (sf::RenderTarget & target, sf::RenderStates states) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Instantiated draw function\&. Instantiated draw function to draw the shape to the screen\&. 
.PP
Implements \fBShapes\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LabBook1 from the source code\&.
