.TH "C:/Users/Bluh1/OneDrive/Desktop/University Work/Year 2/IMAT2905/lab code/labbook1assessed/src/main.cpp" 3 "Sun Oct 30 2022" "LabBook1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Bluh1/OneDrive/Desktop/University Work/Year 2/IMAT2905/lab code/labbook1assessed/src/main.cpp \- Main file for the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'SFML/Graphics\&.hpp'\fP
.br
\fC#include 'Line\&.h'\fP
.br
\fC#include 'Dot\&.h'\fP
.br
\fC#include 'Arc\&.h'\fP
.br
\fC#include 'Square\&.h'\fP
.br
\fC#include 'Triangle\&.h'\fP
.br
\fC#include 'Circle\&.h'\fP
.br
\fC#include 'Hexagon\&.h'\fP
.br
\fC#include 'Octagon\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main file for the application\&. 

Contains the entry point of the application 
.SH "Function Documentation"
.PP 
.SS "int main ()"
Objects are instantiated in the main\&. It will ask for location, size and colour data\&.
.PP
\fBShapes\fP are drawn here\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LabBook1 from the source code\&.
