.TH "md__c___users__bluh1__one_drive__desktop__university__work__year_2__i_m_a_t2905_lab_code_labbook1assessed__r_e_a_d_m_e" 3 "Sun Oct 30 2022" "LabBook1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users__bluh1__one_drive__desktop__university__work__year_2__i_m_a_t2905_lab_code_labbook1assessed__r_e_a_d_m_e \- Lab Book 1 Starter Code 
.PP
Starter Code for lab book 1 - \fBShapes\fP
.PP
You will need to download the external libs from blackbaord\&. You can then clone this repo in the labsfolder\&. 
